#!/usr/bin/env bash
# displays "bad luck" for 4th iteration, "good luck" for 8th and "Best School" for others in range of 10

x=1
while [ $x -le 10 ]
do
    if [ $x -eq 4 ]
    then
	echo "bad luck"
    elif [ $x -eq 8 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi
    
x=$((x + 1))  
done
