#!/usr/bin/env bash
# prints out 1-20 and displays "bad luck from China", "bad luck from Japan" and "bad luck from Italy" at the 4th, 9th and 17th position respectively.

x=1
while [ $x -le 20 ]
do
    case $x in
	4)
	    echo "$x"
	    echo "bad luck from China"
	    ;;
	9)
	    echo "$x"
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "$x"
	    echo "bad luck from Italy"
	    ;;
	*)
	    echo "$x"
	    ;;
    esac 
x=$((x + 1))  
done
